name: rosch
favicon: null
layout_spectrum: 0.0066073189955204725
typography_spectrum: 0.8199375658296049
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6015526996925473
  lightness: 0.301346633117646
  saturation: 0.6599981130566448
  rhythmicContrast: 0.052120708860456944
purpose: []
