name: rosch
favicon: null
layout_spectrum: 0.75364
typography_spectrum: 0.65502
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#baae9e'
    - '#100e0f'
    - '#683b1e'
    - '#877a6a'
    - '#fffef9'
  brandStrength: 0.625
  lightness: 0.301346633117646
  saturation: 0.6599981130566448
  rhythmicContrast: 0.052120708860456944
purpose: []
